package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AacClientes generated by hbm2java
 */
@Entity
@Table(name="aac_clientes"
    ,catalog="db_ana_carvalho"
)
public class AacClientes  implements java.io.Serializable {


     private int aacIdCliente;
     private Integer aacLimiteCredito;
     private String aacLogradouro;
     private Integer aacNumeroEndereco;
     private String aacComplemento;
     private String aacBairro;
     private String aacCidade;
     private String aacEstado;
     private String aacCep;
     private String aacPreferenciaComunicacao;
     private Integer aacTelefone;
     private String aacEmail;
     private String aacUltimoPedido;
     private String aacNome;
     private String aacCpf;
     private Set aacVendases = new HashSet(0);

    public AacClientes() {
    }

	
    public AacClientes(int aacIdCliente) {
        this.aacIdCliente = aacIdCliente;
    }
    public AacClientes(int aacIdCliente, Integer aacLimiteCredito, String aacLogradouro, Integer aacNumeroEndereco, String aacComplemento, String aacBairro, String aacCidade, String aacEstado, String aacCep, String aacPreferenciaComunicacao, Integer aacTelefone, String aacEmail, String aacUltimoPedido, String aacNome, String aacCpf, Set aacVendases) {
       this.aacIdCliente = aacIdCliente;
       this.aacLimiteCredito = aacLimiteCredito;
       this.aacLogradouro = aacLogradouro;
       this.aacNumeroEndereco = aacNumeroEndereco;
       this.aacComplemento = aacComplemento;
       this.aacBairro = aacBairro;
       this.aacCidade = aacCidade;
       this.aacEstado = aacEstado;
       this.aacCep = aacCep;
       this.aacPreferenciaComunicacao = aacPreferenciaComunicacao;
       this.aacTelefone = aacTelefone;
       this.aacEmail = aacEmail;
       this.aacUltimoPedido = aacUltimoPedido;
       this.aacNome = aacNome;
       this.aacCpf = aacCpf;
       this.aacVendases = aacVendases;
    }
   
     @Id 

    
    @Column(name="aac_id_cliente", unique=true, nullable=false)
    public int getAacIdCliente() {
        return this.aacIdCliente;
    }
    
    public void setAacIdCliente(int aacIdCliente) {
        this.aacIdCliente = aacIdCliente;
    }

    
    @Column(name="aac_limite_credito")
    public Integer getAacLimiteCredito() {
        return this.aacLimiteCredito;
    }
    
    public void setAacLimiteCredito(Integer aacLimiteCredito) {
        this.aacLimiteCredito = aacLimiteCredito;
    }

    
    @Column(name="aac_logradouro", length=40)
    public String getAacLogradouro() {
        return this.aacLogradouro;
    }
    
    public void setAacLogradouro(String aacLogradouro) {
        this.aacLogradouro = aacLogradouro;
    }

    
    @Column(name="aac_numero_endereco")
    public Integer getAacNumeroEndereco() {
        return this.aacNumeroEndereco;
    }
    
    public void setAacNumeroEndereco(Integer aacNumeroEndereco) {
        this.aacNumeroEndereco = aacNumeroEndereco;
    }

    
    @Column(name="aac_complemento", length=50)
    public String getAacComplemento() {
        return this.aacComplemento;
    }
    
    public void setAacComplemento(String aacComplemento) {
        this.aacComplemento = aacComplemento;
    }

    
    @Column(name="aac_bairro", length=30)
    public String getAacBairro() {
        return this.aacBairro;
    }
    
    public void setAacBairro(String aacBairro) {
        this.aacBairro = aacBairro;
    }

    
    @Column(name="aac_cidade", length=23)
    public String getAacCidade() {
        return this.aacCidade;
    }
    
    public void setAacCidade(String aacCidade) {
        this.aacCidade = aacCidade;
    }

    
    @Column(name="aac_estado", length=2)
    public String getAacEstado() {
        return this.aacEstado;
    }
    
    public void setAacEstado(String aacEstado) {
        this.aacEstado = aacEstado;
    }

    
    @Column(name="aac_cep", length=8)
    public String getAacCep() {
        return this.aacCep;
    }
    
    public void setAacCep(String aacCep) {
        this.aacCep = aacCep;
    }

    
    @Column(name="aac_preferencia_comunicacao", length=15)
    public String getAacPreferenciaComunicacao() {
        return this.aacPreferenciaComunicacao;
    }
    
    public void setAacPreferenciaComunicacao(String aacPreferenciaComunicacao) {
        this.aacPreferenciaComunicacao = aacPreferenciaComunicacao;
    }

    
    @Column(name="aac_telefone")
    public Integer getAacTelefone() {
        return this.aacTelefone;
    }
    
    public void setAacTelefone(Integer aacTelefone) {
        this.aacTelefone = aacTelefone;
    }

    
    @Column(name="aac_email", length=40)
    public String getAacEmail() {
        return this.aacEmail;
    }
    
    public void setAacEmail(String aacEmail) {
        this.aacEmail = aacEmail;
    }

    
    @Column(name="aac_ultimo_pedido", length=10)
    public String getAacUltimoPedido() {
        return this.aacUltimoPedido;
    }
    
    public void setAacUltimoPedido(String aacUltimoPedido) {
        this.aacUltimoPedido = aacUltimoPedido;
    }

    
    @Column(name="aac_nome", length=45)
    public String getAacNome() {
        return this.aacNome;
    }
    
    public void setAacNome(String aacNome) {
        this.aacNome = aacNome;
    }

    
    @Column(name="aac_cpf", length=11)
    public String getAacCpf() {
        return this.aacCpf;
    }
    
    public void setAacCpf(String aacCpf) {
        this.aacCpf = aacCpf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aacClientes")
    public Set getAacVendases() {
        return this.aacVendases;
    }
    
    public void setAacVendases(Set aacVendases) {
        this.aacVendases = aacVendases;
    }




}


