package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AacFuncionarios generated by hbm2java
 */
@Entity
@Table(name="aac_funcionarios"
    ,catalog="db_ana_carvalho"
)
public class AacFuncionarios  implements java.io.Serializable {


     private int aacIdFuncionario;
     private String aacNome;
     private String aacTipoContratacao;
     private String aacEmailProfissional;
     private String aacMatricula;
     private Integer aacTotalVendas;
     private Date aacDataAdmissao;

    public AacFuncionarios() {
    }

	
    public AacFuncionarios(int aacIdFuncionario) {
        this.aacIdFuncionario = aacIdFuncionario;
    }
    public AacFuncionarios(int aacIdFuncionario, String aacNome, String aacTipoContratacao, String aacEmailProfissional, String aacMatricula, Integer aacTotalVendas, Date aacDataAdmissao) {
       this.aacIdFuncionario = aacIdFuncionario;
       this.aacNome = aacNome;
       this.aacTipoContratacao = aacTipoContratacao;
       this.aacEmailProfissional = aacEmailProfissional;
       this.aacMatricula = aacMatricula;
       this.aacTotalVendas = aacTotalVendas;
       this.aacDataAdmissao = aacDataAdmissao;
    }
   
     @Id 
    
    @Column(name="aac_id_funcionario", unique=true, nullable=false)
    public int getAacIdFuncionario() {
        return this.aacIdFuncionario;
    }
    
    public void setAacIdFuncionario(int aacIdFuncionario) {
        this.aacIdFuncionario = aacIdFuncionario;
    }

    
    @Column(name="aac_nome", length=30)
    public String getAacNome() {
        return this.aacNome;
    }
    
    public void setAacNome(String aacNome) {
        this.aacNome = aacNome;
    }

    
    @Column(name="aac_tipo_contratacao", length=20)
    public String getAacTipoContratacao() {
        return this.aacTipoContratacao;
    }
    
    public void setAacTipoContratacao(String aacTipoContratacao) {
        this.aacTipoContratacao = aacTipoContratacao;
    }

    
    @Column(name="aac_email_profissional", length=40)
    public String getAacEmailProfissional() {
        return this.aacEmailProfissional;
    }
    
    public void setAacEmailProfissional(String aacEmailProfissional) {
        this.aacEmailProfissional = aacEmailProfissional;
    }

    
    @Column(name="aac_matricula", length=20)
    public String getAacMatricula() {
        return this.aacMatricula;
    }
    
    public void setAacMatricula(String aacMatricula) {
        this.aacMatricula = aacMatricula;
    }

    
    @Column(name="aac_total_vendas")
    public Integer getAacTotalVendas() {
        return this.aacTotalVendas;
    }
    
    public void setAacTotalVendas(Integer aacTotalVendas) {
        this.aacTotalVendas = aacTotalVendas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aac_data_admissao", length=10)
    public Date getAacDataAdmissao() {
        return this.aacDataAdmissao;
    }
    
    public void setAacDataAdmissao(Date aacDataAdmissao) {
        this.aacDataAdmissao = aacDataAdmissao;
    }

     @Override
     public String toString(){
         return this.aacNome;
    }
     
     @Override
    public boolean equals(Object object) {
        if (object instanceof AacFuncionarios) {
            AacFuncionarios aacFuncionarios = (AacFuncionarios) object;
            if (aacFuncionarios.getAacIdFuncionario()== this.getAacIdFuncionario()) {
                return true;
            }
        }
        return false;
    }

}


