package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AacProdutos generated by hbm2java
 */
@Entity
@Table(name="aac_produtos"
    ,catalog="db_ana_carvalho"
)
public class AacProdutos  implements java.io.Serializable {


     private int aacIdProdutos;
     private String aacTipoMaterial;
     private Integer aacTamanho;
     private String aacCor;
     private Double aacPreco;
     private String aacMarca;
     private String aacTipoUso;
     private Integer aacNumCompartilhamentos;
     private String aacEstilo;
     private String aacTipoFechamento;

    public AacProdutos() {
    }

	
    public AacProdutos(int aacIdProdutos) {
        this.aacIdProdutos = aacIdProdutos;
    }
    public AacProdutos(int aacIdProdutos, String aacTipoMaterial, Integer aacTamanho, String aacCor, Double aacPreco, String aacMarca, String aacTipoUso, Integer aacNumCompartilhamentos, String aacEstilo, String aacTipoFechamento) {
       this.aacIdProdutos = aacIdProdutos;
       this.aacTipoMaterial = aacTipoMaterial;
       this.aacTamanho = aacTamanho;
       this.aacCor = aacCor;
       this.aacPreco = aacPreco;
       this.aacMarca = aacMarca;
       this.aacTipoUso = aacTipoUso;
       this.aacNumCompartilhamentos = aacNumCompartilhamentos;
       this.aacEstilo = aacEstilo;
       this.aacTipoFechamento = aacTipoFechamento;
    }
   
     @Id 

    @Column(name="aac_id_produtos", unique=true, nullable=false)
    public int getAacIdProdutos() {
        return this.aacIdProdutos;
    }
    
    public void setAacIdProdutos(int aacIdProdutos) {
        this.aacIdProdutos = aacIdProdutos;
    }

    
    @Column(name="aac_tipo_material", length=10)
    public String getAacTipoMaterial() {
        return this.aacTipoMaterial;
    }
    
    public void setAacTipoMaterial(String aacTipoMaterial) {
        this.aacTipoMaterial = aacTipoMaterial;
    }

    
    @Column(name="aac_tamanho", length=1)
    public Integer getAacTamanho() {
        return this.aacTamanho;
   }
    
    public void setAacTamanho(Integer aacTamanho) {
        this.aacTamanho = aacTamanho;
    }

    
    @Column(name="aac_cor", length=15)
    public String getAacCor() {
        return this.aacCor;
    }
    
    public void setAacCor(String aacCor) {
        this.aacCor = aacCor;
    }

    
    @Column(name="aac_preco")
    public Double getAacPreco() {
        return this.aacPreco;
    }
    
    public void setAacPreco(Double aacPreco) {
        this.aacPreco = aacPreco;
    }

    
    @Column(name="aac_marca", length=20)
    public String getAacMarca() {
        return this.aacMarca;
    }
    
    public void setAacMarca(String aacMarca) {
        this.aacMarca = aacMarca;
    }

    
    @Column(name="aac_tipo_uso", length=15)
    public String getAacTipoUso() {
        return this.aacTipoUso;
    }
    
    public void setAacTipoUso(String aacTipoUso) {
        this.aacTipoUso = aacTipoUso;
    }

    
    @Column(name="aac_num_compartilhamentos")
    public Integer getAacNumCompartilhamentos() {
        return this.aacNumCompartilhamentos;
    }
    
    public void setAacNumCompartilhamentos(Integer aacNumCompartilhamentos) {
        this.aacNumCompartilhamentos = aacNumCompartilhamentos;
    }

    
    @Column(name="aac_estilo", length=10)
    public String getAacEstilo() {
        return this.aacEstilo;
    }
    
    public void setAacEstilo(String aacEstilo) {
        this.aacEstilo = aacEstilo;
    }

    
    @Column(name="aac_tipo_fechamento", length=10)
    public String getAacTipoFechamento() {
        return this.aacTipoFechamento;
    }
    
    public void setAacTipoFechamento(String aacTipoFechamento) {
        this.aacTipoFechamento = aacTipoFechamento;
    }


     @Override
     public String toString(){
         return this.aacMarca;
    }


}


