package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AacUsuarios generated by hbm2java
 */
@Entity
@Table(name="aac_usuarios"
    ,catalog="db_ana_carvalho"
)
public class AacUsuarios  implements java.io.Serializable {


     private int aacIdUsuarios;
     private String aacNomeCompleto;
     private String aacApelido;
     private String aacCpf;
     private Date aacDataNascimento;
     private String aacSenha;
     private Integer aacNivell;
     private Character aacAtivo;

    public AacUsuarios() {
    }

	
    public AacUsuarios(int aacIdUsuarios) {
        this.aacIdUsuarios = aacIdUsuarios;
    }
    public AacUsuarios(int aacIdUsuarios, String aacNomeCompleto, String aacApelido, String aacCpf, Date aacDataNascimento, String aacSenha, Integer aacNivell, Character aacAtivo) {
       this.aacIdUsuarios = aacIdUsuarios;
       this.aacNomeCompleto = aacNomeCompleto;
       this.aacApelido = aacApelido;
       this.aacCpf = aacCpf;
       this.aacDataNascimento = aacDataNascimento;
       this.aacSenha = aacSenha;
       this.aacNivell = aacNivell;
       this.aacAtivo = aacAtivo;
    }
   
     @Id 

    
    @Column(name="aac_id_usuarios", unique=true, nullable=false)
    public int getAacIdUsuarios() {
        return this.aacIdUsuarios;
    }
    
    public void setAacIdUsuarios(int aacIdUsuarios) {
        this.aacIdUsuarios = aacIdUsuarios;
    }

    
    @Column(name="aac_nome_completo", length=50)
    public String getAacNomeCompleto() {
        return this.aacNomeCompleto;
    }
    
    public void setAacNomeCompleto(String aacNomeCompleto) {
        this.aacNomeCompleto = aacNomeCompleto;
    }

    
    @Column(name="aac_apelido", length=25)
    public String getAacApelido() {
        return this.aacApelido;
    }
    
    public void setAacApelido(String aacApelido) {
        this.aacApelido = aacApelido;
    }

    
    @Column(name="aac_cpf", length=14)
    public String getAacCpf() {
        return this.aacCpf;
    }
    
    public void setAacCpf(String aacCpf) {
        this.aacCpf = aacCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aac_data_nascimento", length=10)
    public Date getAacDataNascimento() {
        return this.aacDataNascimento;
    }
    
    public void setAacDataNascimento(Date aacDataNascimento) {
        this.aacDataNascimento = aacDataNascimento;
    }

    
    @Column(name="aac_senha", length=20)
    public String getAacSenha() {
        return this.aacSenha;
    }
    
    public void setAacSenha(String aacSenha) {
        this.aacSenha = aacSenha;
    }

    
    @Column(name="aac_nivell")
    public Integer getAacNivell() {
        return this.aacNivell;
    }
    
    public void setAacNivell(Integer aacNivell) {
        this.aacNivell = aacNivell;
    }

    
    @Column(name="aac_ativo", length=1)
    public Character getAacAtivo() {
        return this.aacAtivo;
    }
    
    public void setAacAtivo(Character aacAtivo) {
        this.aacAtivo = aacAtivo;
    }




}


