package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AacVendas generated by hbm2java
 */
@Entity
@Table(name="aac_vendas"
    ,catalog="db_ana_carvalho"
)
public class AacVendas  implements java.io.Serializable {


     private int aacIdVendas;
     private AacClientes aacClientes;
     private AacFuncionarios aacFuncionarios;
     private Date aacDataVenda;
 

    public AacVendas() {
    }

	
    public AacVendas(int aacIdVendas, AacClientes aacClientes, AacFuncionarios aacFuncionarios, Date aacDataVenda) {
        this.aacIdVendas = aacIdVendas;
        this.aacClientes = aacClientes;
        this.aacFuncionarios = aacFuncionarios;
        this.aacDataVenda = aacDataVenda;
    }
    public AacVendas(int aacIdVendas, AacClientes aacClientes, AacFuncionarios aacFuncionarios, Date aacDataVenda, String aacStatus) {
       this.aacIdVendas = aacIdVendas;
       this.aacClientes = aacClientes;
       this.aacFuncionarios = aacFuncionarios;
       this.aacDataVenda = aacDataVenda;

    }
   
     @Id 
    
    @Column(name="aac_id_vendas", unique=true, nullable=false)
    public int getAacIdVendas() {
        return this.aacIdVendas;
    }
    
    public void setAacIdVendas(int aacIdVendas) {
        this.aacIdVendas = aacIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_clientes", nullable=false)
    public AacClientes getAacClientes() {
        return this.aacClientes;
    }
    
    public void setAacClientes(AacClientes aacClientes) {
        this.aacClientes = aacClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_funcionarios", nullable=false)
    public AacFuncionarios getAacFuncionarios() {
        return this.aacFuncionarios;
    }
    
    public void setAacFuncionarios(AacFuncionarios aacFuncionarios) {
        this.aacFuncionarios = aacFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aac_data_venda", nullable=false, length=10)
    public Date getAacDataVenda() {
        return this.aacDataVenda;
    }
    
    public void setAacDataVenda(Date aacDataVenda) {
        this.aacDataVenda = aacDataVenda;
    }
}


