package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AacVendas generated by hbm2java
 */
@Entity
@Table(name="aac_vendas"
    ,catalog="db_ana_carvalho"
)
public class AacVendas  implements java.io.Serializable {


     private int aacIdVendas;
     private AacClientes aacClientes;
     private AacFuncionarios aacFuncionarios;
     private Date aacDataVenda;
     private BigDecimal aacValorTotal;
     private Date aacDataEntrega;
     private String aacStatus;
 

    public AacVendas() {
    }

	
    public AacVendas(int aacIdVendas, AacClientes aacClientes, AacFuncionarios aacFuncionarios, Date aacDataVenda, BigDecimal aacValorTotal, Date aacDataEntrega, String aacStatus) {
        this.aacIdVendas = aacIdVendas;
        this.aacClientes = aacClientes;
        this.aacFuncionarios = aacFuncionarios;
        this.aacDataVenda = aacDataVenda;
        this.aacValorTotal = aacValorTotal;
        this.aacDataEntrega = aacDataEntrega;
        this.aacStatus = aacStatus;
    }
    public AacVendas(int aacIdVendas, AacClientes aacClientes, AacFuncionarios aacFuncionarios, Date aacDataVenda, BigDecimal aacValorTotal, Date aacDataEntrega, String aacStatus, Set aacVendasProdutoses) {
       this.aacIdVendas = aacIdVendas;
       this.aacClientes = aacClientes;
       this.aacFuncionarios = aacFuncionarios;
       this.aacDataVenda = aacDataVenda;
       this.aacValorTotal = aacValorTotal;
       this.aacDataEntrega = aacDataEntrega;
       this.aacStatus = aacStatus;
    }
   
     @Id 
    
    @Column(name="aac_id_vendas", unique=true, nullable=false)
    public int getAacIdVendas() {
        return this.aacIdVendas;
    }
    
    public void setAacIdVendas(int aacIdVendas) {
        this.aacIdVendas = aacIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_clientes", nullable=false)
    public AacClientes getAacClientes() {
        return this.aacClientes;
    }
    
    public void setAacClientes(AacClientes aacClientes) {
        this.aacClientes = aacClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_funcionarios", nullable=false)
    public AacFuncionarios getAacFuncionarios() {
        return this.aacFuncionarios;
    }
    
    public void setAacFuncionarios(AacFuncionarios aacFuncionarios) {
        this.aacFuncionarios = aacFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aac_data_venda", nullable=false, length=10)
    public Date getAacDataVenda() {
        return this.aacDataVenda;
    }
    
    public void setAacDataVenda(Date aacDataVenda) {
        this.aacDataVenda = aacDataVenda;
    }

    
    @Column(name="aac_valor_total", nullable=false, precision=12)
    public BigDecimal getAacValorTotal() {
        return this.aacValorTotal;
    }
    
    public void setAacValorTotal(BigDecimal aacValorTotal) {
        this.aacValorTotal = aacValorTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aac_data_entrega", nullable=false, length=10)
    public Date getAacDataEntrega() {
        return this.aacDataEntrega;
    }
    
    public void setAacDataEntrega(Date aacDataEntrega) {
        this.aacDataEntrega = aacDataEntrega;
    }

    
    @Column(name="aac_status", nullable=false, length=20)
    public String getAacStatus() {
        return this.aacStatus;
    }
    
    public void setAacStatus(String aacStatus) {
        this.aacStatus = aacStatus;
    }




}


