package bean;
// Generated 11/out/2025 18:49:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AacVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="aac_vendas_produtos"
    ,catalog="db_ana_carvalho"
)
public class AacVendasProdutos  implements java.io.Serializable {


     private int aacIdVendasProdutos;
     private AacProdutos aacProdutos;
     private AacVendas aacVendas;

    public AacVendasProdutos() {
    }

    public AacVendasProdutos(int aacIdVendasProdutos, AacProdutos aacProdutos, AacVendas aacVendas, byte aacUnidades, BigDecimal aacPrecoUnitario, BigDecimal aacDesconto) {
       this.aacIdVendasProdutos = aacIdVendasProdutos;
       this.aacProdutos = aacProdutos;
       this.aacVendas = aacVendas;
    }
   
     @Id 


    @Column(name="aac_id_vendas_produtos", unique=true, nullable=false)
    public int getAacIdVendasProdutos() {
        return this.aacIdVendasProdutos;
    }
    
    public void setAacIdVendasProdutos(int aacIdVendasProdutos) {
        this.aacIdVendasProdutos = aacIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_produtos", nullable=false)
    public AacProdutos getAacProdutos() {
        return this.aacProdutos;
    }
    
    public void setAacProdutos(AacProdutos aacProdutos) {
        this.aacProdutos = aacProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aac_fk_vendas", nullable=false)
    public AacVendas getAacVendas() {
        return this.aacVendas;
    }
    
    public void setAacVendas(AacVendas aacVendas) {
        this.aacVendas = aacVendas;
    }
}


